---
- name: Revert deployment of HDFS cluster charts
  hosts: leader
  vars_files:
    - ../vars.yaml
  become: yes
  tasks:
    - name: Remove Zookeeper chart
      kubernetes.core.k8s:
        name: zookeeper
        namespace: "{{ k8s_namespace }}"
        state: absent

    - name: Remove Zookeeper ZNode chart
      kubernetes.core.k8s:
        name: hdfs-znode
        namespace: "{{ k8s_namespace }}"
        state: absent

    - name: Remove HDFS chart
      kubernetes.core.k8s:
        name: "{{ hdfs_clustername }}"
        namespace: "{{ k8s_namespace }}"
        state: absent

- name: Revert spark-operator deployment
  hosts: leader
  vars_files:
    - ../vars.yaml
  become: yes
  tasks:
    - name: Remove spark-operator helm chart
      kubernetes.core.helm:
        name: spark-operator
        state: absent
        release_namespace: "{{ k8s_namespace }}"

    - name: Remove spark-operator repository
      kubernetes.core.helm_repository:
        name: spark-operator
        state: absent

- name: Revert MongoDB deployment
  hosts: leader
  vars_files:
    - ../vars.yaml
  become: yes
  tasks:
    - name: Remove mongodb helm chart
      kubernetes.core.helm:
        name: mongodb
        state: absent
        release_namespace: "{{ k8s_namespace }}"

- name: Revert HDFS Operator deployments
  hosts: leader
  vars_files:
    - ../vars.yaml
  become: yes
  tasks:
    - name: Remove Zookeeper operator helm chart
      kubernetes.core.helm:
        name: zookeeper-operator
        state: absent
        release_namespace: "{{ k8s_namespace }}"

    - name: Remove HDFS operator helm chart
      kubernetes.core.helm:
        name: hdfs-operator
        state: absent
        release_namespace: "{{ k8s_namespace }}"

    - name: Remove Commons operator helm chart
      kubernetes.core.helm:
        name: commons-operator
        state: absent
        release_namespace: "{{ k8s_namespace }}"

    - name: Remove Secret operator helm chart
      kubernetes.core.helm:
        name: secret-operator
        state: absent
        release_namespace: "{{ k8s_namespace }}"

    - name: Remove Listener operator helm chart
      kubernetes.core.helm:
        name: listener-operator
        state: absent
        release_namespace: "{{ k8s_namespace }}"

    - name: Remove stackable-stable repository
      kubernetes.core.helm_repository:
        name: stackable-stable
        state: absent

- name: Remove bind-mount directories for PersistentVolumes on all nodes
  hosts: remote
  become: yes
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Unmount mongodb directories
      ansible.posix.mount:
        path: "/mnt/disks/mongodb-data-{{ ansible_hostname | lower }}"
        state: unmounted
      loop: "{{ range(1, replica_count + 1) }}"

    - name: Unmount zookeeper directories
      ansible.posix.mount:
        path: "/mnt/disks/zookeeper-data-{{ ansible_hostname | lower }}"
        state: unmounted

    - name: Unmount hdfs directories
      ansible.posix.mount:
        path: "/mnt/disks/hdfs-data-{{ ansible_hostname | lower }}-{{ item }}"
        state: unmounted
      loop: "{{ range(1, data_node_replicas + name_node_replicas + journal_node_replicas + 1) }}"

    - name: Remove mongodb data source directory
      ansible.builtin.file:
        path: "/mnt/disks/mongodb-data-{{ ansible_hostname | lower }}"
        state: absent
      loop: "{{ range(1, replica_count + 1) }}"

    - name: Remove Zookeeper data source directory
      ansible.builtin.file:
        path: "/mnt/disks/zookeeper-data-{{ ansible_hostname | lower }}"
        state: absent

    - name: Remove HDFS data source directory
      ansible.builtin.file:
        path: "/mnt/disks/hdfs-data-{{ ansible_hostname | lower }}-{{ item }}"
        state: absent
      loop: "{{ range(1, data_node_replicas + name_node_replicas + journal_node_replicas + 1) }}"

    - name: Remove mongodb data target directory
      ansible.builtin.file:
        path: "/mongodb-data-{{ ansible_hostname | lower }}"
        state: absent
      loop: "{{ range(1, replica_count + 1) }}"

    - name: Remove Zookeeper data target directory
      ansible.builtin.file:
        path: "/zookeeper-data-{{ ansible_hostname | lower }}"
        state: absent

    - name: Remove HDFS data target directory
      ansible.builtin.file:
        path: "/hdfs-data-{{ ansible_hostname | lower }}-{{ item }}"
        state: absent
      loop: "{{ range(1, data_node_replicas + name_node_replicas + journal_node_replicas + 1) }}"

- name: Remove temporary template dir
  hosts: leader
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Remove temporary directory for templating
      ansible.builtin.file:
        path: /tmp/charts
        state: absent
