---
- name: Revert deployments
  hosts: leader
  vars_files:
    - ../vars.yaml
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python3"
  become: true
  ignore_errors: true
  tasks:
    - name: Remove spark-operator helm chart
      kubernetes.core.helm:
        name: spark-operator
        release_namespace: "{{ k8s_namespace }}"
        state: absent
        wait: true

    - name: Remove spark-operator repository
      kubernetes.core.helm_repository:
        name: spark-operator
        state: absent

    - name: Remove mongodb helm chart
      kubernetes.core.helm:
        name: mongodb
        release_namespace: "{{ k8s_namespace }}"
        state: absent
        wait: true

    - name: Remove kube-prometheus-stack Helm release
      kubernetes.core.helm:
        name: kube-prometheus-stack
        state: absent
        release_namespace: "{{ k8s_namespace }}"
        wait: true

    - name: Remove prometheus-community repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        state: absent

- name: Remove bind-mount directories for PersistentVolumes on all nodes
  hosts: remote
  become: true
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Unmount mongodb directories
      ansible.posix.mount:
        path: "/mnt/disks/mongodb-data-{{ ansible_hostname | lower }}"
        state: unmounted
      loop: "{{ range(1, replica_count + 1) }}"

    - name: Remove mongodb data source directory
      file:
        path: "/mnt/disks/mongodb-data-{{ ansible_hostname | lower }}"
        state: absent
      loop: "{{ range(1, replica_count + 1) }}"

    - name: Remove mongodb data target directory
      file:
        path: "{{ user_dir }}/mongodb-data-{{ ansible_hostname | lower }}"
        state: absent
      loop: "{{ range(1, replica_count + 1) }}"

- name: Delete pending SparkApplications
  hosts: leader
  vars_files:
    - ../vars.yaml
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python3"
  become: true
  ignore_errors: true
  tasks:
    - name: Retrieve all SparkApplications in the namespace
      kubernetes.core.k8s_info:
        api_version: sparkoperator.k8s.io/v1beta2
        kind: SparkApplication
        namespace: "{{ k8s_namespace }}"
      register: spark_app_info

    - name: Extract SparkApplication names
      set_fact:
        spark_app_names: "{{ spark_app_info.resources | map(attribute='metadata.name') | list }}"

    - name: Delete SparkApplications
      kubernetes.core.k8s:
        api_version: sparkoperator.k8s.io/v1beta2
        kind: SparkApplication
        name: "{{ item }}"
        namespace: "{{ k8s_namespace }}"
        state: absent
      loop: "{{ spark_app_names }}"
      when: spark_app_names | length > 0

- name: Delete all PVCs in a namespace
  hosts: leader
  vars_files:
    - ../vars.yaml
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python3"
  become: true
  tasks:
    - name: Retrieve all PVCs in the namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ k8s_namespace }}"
      register: pvc_info

    - name: Extract PVC names
      set_fact:
        pvc_names: "{{ pvc_info.resources | map(attribute='metadata.name') | list }}"

    - name: Delete PVCs
      kubernetes.core.k8s:
        kind: PersistentVolumeClaim
        name: "{{ item }}"
        namespace: "{{ k8s_namespace }}"
        state: absent
      loop: "{{ pvc_names }}"
      when: pvc_names | length > 0

- name: Delete all PVs in the namespace
  hosts: leader
  vars_files:
    - ../vars.yaml
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python3"
  become: true
  tasks:
    - name: Retrieve all PVs in the namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: PersistentVolume
        namespace: "{{ k8s_namespace }}"
      register: pv_info

    - name: Extract PV names
      set_fact:
        pv_names: "{{ pv_info.resources | map(attribute='metadata.name') | list }}"

    - name: Delete PVs
      kubernetes.core.k8s:
        kind: PersistentVolume
        state: absent
        name: "{{ item }}"
        namespace: "{{ k8s_namespace }}"
      loop: "{{ pv_names }}"
      when: pv_names | length > 0

- name: Cleanup leader
  hosts: leader
  vars_files:
    - ../vars.yaml
  become: true
  tasks:
    - name: Stop Hadoop services
      ignore_errors: true
      become_user: "{{ linux_username }}"
      command: "{{ hadoop_dir }}/sbin/stop-all.sh"

    - name: Remove users dir
      file:
        path: "{{ user_dir }}"
        state: absent

- name: Revert user creation
  hosts: remote
  vars_files:
    - ../vars.yaml
  become: true
  become_user: root
  tasks:
    - name: Remove new user from sudo group
      user:
        name: "{{ linux_username }}"
        groups: sudo
        append: no
        state: present

    - name: Remove passwordless sudo for the new user
      lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: "^%{{ linux_username }}"

    - name: Delete the user
      user:
        name: "{{ linux_username }}"
        state: absent
        remove: yes
