---
# When changing the hibench.conf in any way, e.g. when changing the scale, we need to recompile its modules
- name: Build and deploy HiBench
  hosts: leader
  become: true
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Template Hadoop config
      template:
        src: "{{ hibench_template_dir }}/hadoop.conf"
        dest: "{{ hibench_dir }}/conf/hadoop.conf"

    - name: Template HiBench config
      template:
        src: "{{ hibench_template_dir }}/hibench.conf"
        dest: "{{ remote_template_dir }}/hibench.conf"

    - name: Replace default hibench.conf
      copy:
        src: "{{ remote_template_dir }}/hibench.conf"
        dest: "{{ hibench_dir }}/conf/hibench.conf"
        remote_src: yes

    - name: Template Spark config
      template:
        src: "{{ hibench_template_dir }}/spark.conf"
        dest: "{{ hibench_dir }}/conf/spark.conf"

    - name: Build HiBench (This might take > 1h initially because there are artifacts downloaded with several 100 MB)
      shell:
        cmd: "mvn -Psparkbench -Dspark={{ spark_hibench_profile }} -Dscala={{ scala_hibench_profile }} clean package"
        chdir: "{{ hibench_dir }}"

    # generated workloads are automatically submitted to HDFS - if the script is stuck here, the machine likely has
    # not enough resources
    - name: Run prepare script
      command: bash "{{ hibench_dir }}/bin/workloads/{{ item }}/prepare/prepare.sh"
      loop:
        - "micro/wordcount"

    - name: Check for generated workloads
      cmd: "{{ hadoop_dir }}/bin/hdfs dfs -ls /HiBench/{{  }}"
      loop:
        - "micro/wordcount"

    - name: Run run_script_modifier.py to generate adjusted HiBench run scripts
      shell:
        cmd: "{{ local_scripts_dir }}/run_script_modifier.py"
        chdir: "{{ hibench_dir }}"

    - name: Copy scripts


#      bin/hdfs dfs -ls /HiBench/Kmeans/Input
#      Found 3 items
#      drwxr-xr-x   - mtuser supergroup          0 2024-09-20 17:00 /HiBench/Kmeans/Input/cluster
#      drwxr-xr-x   - mtuser supergroup          0 2024-09-20 17:00 /HiBench/Kmeans/Input/samples
#      drwxr-xr-x   - mtuser supergroup          0 2024-09-20 16:59 /HiBench/Kmeans/Input/samples-seeds
