apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{ name }}
spec:
  type: Scala
  mode: cluster
  image: "bitnami/spark:{{ spark_version }}"
  imagePullPolicy: Always
  mainClass: "{{ hibench_main_class }}"
  mainApplicationFile: "{{ hibench_jar }}"
  arguments:
    {% for argument in arguments -%}
    - "{{ argument }}"
    {% endfor %}
  sparkVersion: {{ spark_version }}
  sparkUIOptions:
    serviceLabels:
      test-label/v1: "true"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    labels:
      version: {{ spark_version }}
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    labels:
      version: {{ spark_version }}
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  deps:
    jars:
      - "{{ listener_jar }}"
  sparkConf:
    "spark.extraListeners": "de.tu_berlin.jarnhold.listener.CentralizedSparkListener"
