apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: {{ name }}
spec:
  type: Scala
  mode: cluster
  image: "{{ spark_image }}"
  imagePullPolicy: Always
  mainClass: "{{ hibench_main_class }}"
  mainApplicationFile: "{{ hibench_jar }}"
  arguments:
    {% for argument in arguments -%}
    - "{{ argument }}"
    {% endfor %}
  sparkVersion: "{{ spark_version }}"
  restartPolicy:
    type: Never
  driver:
    memory: "{{ driver_memory }}"
    labels:
      version: "{{ spark_version }}"
    serviceAccount: spark-operator-spark
    configMaps:
      - name: hibench-config
        path: /mnt/config-maps
    env:
      - name: SPARKBENCH_PROPERTIES_FILES
        value: /mnt/config-maps/hibench.conf
  executor:
    memory: "{{ executor_memory }}"
    labels:
      version: "{{ spark_version }}"
    configMaps:
      - name: hibench-config
        path: /mnt/config-maps
    env:
      - name: SPARKBENCH_PROPERTIES_FILES
        value: /mnt/config-maps/hibench.conf
  deps:
    jars:
      - "{{ listener_jar }}"
  sparkConf:
    "spark.extraListeners": "de.tu_berlin.jarnhold.listener.CentralizedSparkListener"
    "spark.customExtraListener.isAdaptive": "{{ is_adaptive }}"
    "spark.customExtraListener.bridgeServiceAddress": "{{ bridgeServiceAddress }}"
