---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  image:
    productVersion: {{ zookeeper_version }}
  servers:
    roleGroups:
      default:
        replicas: {{ zookeeper_replicas }}
        config:
          resources:
            cpu:
              max: {{ zookeeper_cpu_limit }}
            storage:
              data:
                storageClass: {{ storage_class }}
