---
apiVersion: hdfs.stackable.tech/v1alpha1
kind: HdfsCluster
metadata:
  name: {{ hdfs_cluster_name }}
spec:
  image:
    productVersion: {{ hdfs_version }}
  clusterConfig:
    zookeeperConfigMapName: hdfs-znode
    dfsReplication: 1
  nameNodes:
    config:
      listenerClass: external-stable
    roleGroups:
      default:
        replicas: {{ name_node_replicas }}
  dataNodes:
    config:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: {{ data_node_replicas }}
  journalNodes:
    roleGroups:
      default:
        replicas: {{ journal_node_replicas }}
