# all cloud machines
remote:
  hosts:
    leaderNode:
      ansible_host: 34.32.46.55
    workerNode1:
      ansible_host: 34.32.63.52
    workerNode2:
      ansible_host: 34.32.62.193
    workerNode3:
      ansible_host: 34.32.60.85

# 1 host coordinating k8s via kubectl/helm, running bridge service, scaling services, database, etc.
leader:
  hosts:
    leaderNode:

# all machines that contain the batch processing framework and/or hdfs
follower:
  hosts:
    leaderNode:
    workerNode1:
    workerNode2:
    workerNode3:
