# all cloud machines
remote:
  hosts:
    leaderNode:
      ansible_host: 34.32.64.162
    workerNode1:
      ansible_host: 34.32.9.80
    workerNode2:
      ansible_host: 34.32.33.203
    workerNode3:
      ansible_host: 34.32.52.183

# 1 host coordinating k8s via kubectl/helm, running bridge service, scaling services, database, etc.
leader:
  hosts:
    leaderNode:

# all machines that contain the batch processing framework and/or hdfs
follower:
  hosts:
    leaderNode:
    workerNode1:
    workerNode2:
    workerNode3:
