# all cloud machines
remote:
  hosts:
    leaderNode:
      ansible_host: 34.32.39.247
    workerNode1:
      ansible_host: 34.32.39.9
    workerNode2:
      ansible_host: 34.32.47.79

# 1 host coordinating k8s via kubectl/helm, running bridge service, scaling services, database, etc.
leader:
  hosts:
    leaderNode:

# all machines that contain the batch processing framework and/or hdfs
follower:
  hosts:
    leaderNode:
    workerNode1:
    workerNode2:
