# all cloud machines
remote:
  hosts:
    leaderNode:
      ansible_host: 51.144.52.54
      ip: 10.240.0.10
    workerNode1:
      ansible_host: 52.166.3.96
      ip: 10.240.0.20
    workerNode2:
      ansible_host: 52.178.43.155
      ip: 10.240.0.21
    workerNode3:
      ansible_host: 40.68.142.67
      ip: 10.240.0.22
    workerNode4:
      ansible_host: 40.68.142.46
      ip: 10.240.0.23
    workerNode5:
      ansible_host: 13.95.30.88
      ip: 10.240.0.24

# 1 host coordinating k8s via kubectl/helm, running bridge service, scaling services, database, etc.
leader:
  hosts:
    leaderNode:

# all machines that contain the batch processing framework and/or hdfs
follower:
  hosts:
    workerNode1:
    workerNode2:
    workerNode3:
    workerNode4:
    workerNode5:
