 # versions
java_version: "8"
helm_version: "3.15.1"
spark_operator_version: "1.4.6"
mongo_db_chart_version: "15.6.14"
# HiBench/Spark related versions (No support after Spark#3.1.1 as of oktober 2024)
hdfs_version: "3.3.4"
spark_version: "3.1.1"
spark_image: "apache/spark:v3.1.3" # No public available 3.1.1 image found as of oktober 2024
scala_version: "2.12.20"
hadoop_version: "3.2.4"
hibench_version: "827c9f6"
spark_hibench_profile: "3.1"
scala_hibench_profile: "2.12"

# general
listener_jar: "listener_2.12-0.1.0-SNAPSHOT.jar"

# this user can be used for ansible scripts and experiment execution
linux_username: "mtuser"
linux_password: "Admin1!"
hdfs_group: "hdfs"

# Kubernetes
k8s_namespace: "default"
storage_class: "local-storage"

# MongoDB
replica_count: 1
replica_set_name: "rs0"
mongodb_database: "test"
mongodb_username: "test"
mongodb_root_username: "root"
mongodb_password: "Password1!"
mongodb_resource_preset: "nano"

# HDFS
hdfs_address: "hdfs://{{ leader_ip }}:9000" # leader_ip must be set dynamically in the respective task
hdfs_replication_factor: 1

# local paths
working_dir: "{{ lookup('env', 'PWD') }}"
ansible_dir: "{{ working_dir }}/ansible"
local_template_dir: "{{ ansible_dir }}/templates"
hibench_template_dir: "{{ local_template_dir }}/hibench"
hadoop_template_dir: "{{ local_template_dir }}/hadoop"
local_scripts_dir: "{{ ansible_dir }}/scripts"

# remote paths
user_dir: "/home/{{ linux_username }}"
venv_path: "{{ user_dir }}/venv"
remote_template_dir: "{{ user_dir }}/templates"
hadoop_dir: "{{ user_dir }}/hadoop"
hibench_dir: "{{ user_dir }}/hibench"
archives_dir: "{{ user_dir }}/archives"
hdfs_user_dir: "/user/{{ linux_username }}"
