# versions
java_version: "17"
helm_version: "3.15.1"
spark_operator_version: "1.4.2"
mongo_db_chart_version: "15.6.14"
stackable_operator_version: "24.3.0"
zookeeper_version: "3.8.4"
hdfs_version: "3.3.4"
spark_version: "3.5.0"

# linux
username: "mtuser"
password: "Admin1!"

# k8s
k8s_namespace: "default"
persistent_volume_per_node: "100Gi"
storage_class: "local-storage"

# mongodb
replica_count: 2
mongodb_database: "test"
mongodb_username: "test"
mongodb_password: "Password1!"

# hdfs
hdfs_cluster_name: "hdfs-cluster"
zookeeper_replicas: 1
replication_factor: 3 # should be <= data_node_replicas
data_node_replicas: 4
name_node_replicas: 2 # < 2 nodes require disabling shared_edits_dir in ansible/charts/hdfs-cluster.yaml
journal_node_replicas: 1
hdfs_datanode_capacity: "75Gi"
