from decouple import config


class Config:
    KUBECONFIG = config('KUBECONFIG')
    KUBERNETES_NAMESPACE = config('KUBERNETES_NAMESPACE')
    MONGODB_DATABASE = config('MONGODB_DATABASE')
    MONGODB_CONNECTION_STRING = config('MONGODB_CONNECTION_STRING')
    HDFS_CLUSTER_NAME = config('HDFS_CLUSTER_NAME')
